# Generated by Django 5.0.7 on 2024-08-02 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 8, 2, 0, 57, 20, 37404, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
