# Generated by Django 5.0.7 on 2024-08-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_contact_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_activ',
            field=models.BooleanField(default=False),
        ),
    ]
