# Generated by Django 5.0.7 on 2024-08-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_contact_is_activ'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
