# Generated by Django 5.1 on 2024-08-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_catagory_remove_contact_slug_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/product'),
        ),
    ]
