# Generated by Django 5.1 on 2024-08-20 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('relationship', models.CharField(max_length=80)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.contact')),
            ],
        ),
    ]
