# Generated by Django 5.1 on 2024-08-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_familymember'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/product'),
        ),
    ]
