# Generated by Django 5.1 on 2024-08-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
